language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.4
  - nightly
env:
  matrix:
    - JULIA_NUM_THREADS=1
    - JULIA_NUM_THREADS=3 #3 allows the @spawn test to run effectively
jobs:
  exclude:
  - julia: 1.0 # Disable Threads testing
    env: JULIA_NUM_THREADS=3
# script:
#   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#   - julia --project -e 'using Pkg; Pkg.build();'
#   - JULIA_NUM_THREADS=2 julia --project -e 'using Pkg; Pkg.test(; coverage=true)'
notifications:
  email: false
git:
  depth: 9999999
